### ISSUE TITLE
Question about the paper - Occupancy

### ISSUE THREAD

**Issue by Julien-Gustin** [facebookresearch/MCC#3]
Thank you for this wonderful work,

I have a question about the model, why do you predict the occupancy of the surface of the object and not the occupancy of a point lying inside the object such as OccNet does.

> _A query is considered “occupied” (positive) if it is located within radius τ = 0.1 to a ground truth point, and “unoccupied” (negative) otherwise._

And do you think it can be upgraded for thus task in a setting w/o RGB images.

**Comment by chaoyuaw** [comment]
Hi @Julien-Gustin, 

Thanks for the great question!

OccNets assume having access to meshes, and had to convert all of them into watertight meshes, so that inside/outside can be determined. In our case, we don't have meshes, and the point clouds come from CO3D SfM which correspond to the surface points. 

That being said, if one has watertight meshes available and prefers to have inside/outside occupancy output, I think adapting MCC for that makes sense too.
