### ISSUE TITLE
Could it work on human reconstruction?

### ISSUE THREAD

**Issue by Yuanhong-Zheng** [facebookresearch/MCC#6]
Awesome work!I want to know could it work on 3D human reconstruction?Thanks

**Comment by chaoyuaw** [comment]
Hi @Yuanhong200727, 

Thanks for the question!

Since MCC is category agnostic, in theory it should work! In the meantime, human is a special and well-studied category. A specialized human-reconstruction model might work better than the general-purpose MCC. If you give it a try, let us know how it goes!
